package kg.rental.enums;

public enum UserState {
    IDLE,
    RENT_OUT_DISTRICT, RENT_OUT_ROOMS, RENT_OUT_PRICE,
    RENT_OUT_FURNITURE, RENT_OUT_UTILITIES, RENT_OUT_TENANT_TYPE,
    RENT_OUT_CONTACT, RENT_OUT_PHOTOS, RENT_OUT_DESCRIPTION,
    RENT_IN_DISTRICT, RENT_IN_BUDGET, RENT_IN_ROOMS,
    RENT_IN_WHEN, RENT_IN_DESCRIPTION,
    ROOMMATE_SEEK_DISTRICT, ROOMMATE_SEEK_BUDGET, ROOMMATE_SEEK_GENDER,
    ROOMMATE_SEEK_PREFERRED, ROOMMATE_SEEK_SPOTS,
    ROOMMATE_SEEK_WHEN, ROOMMATE_SEEK_DESCRIPTION,
    ROOMMATE_OFFER_TYPE,
    ROOMMATE_OFFER_DISTRICT, ROOMMATE_OFFER_PRICE, ROOMMATE_OFFER_SPOTS,
    ROOMMATE_OFFER_GENDER, ROOMMATE_OFFER_AMENITIES,
    ROOMMATE_OFFER_PHOTOS, ROOMMATE_OFFER_DESCRIPTION,
    MY_LISTINGS,
    SETTINGS,
    SUB_CHOOSE_TYPE,
    SUB_CHOOSE_DISTRICT,
    // Сниму комнату
    RENT_ROOM_IN_DISTRICT,
    RENT_ROOM_IN_BUDGET,
    RENT_ROOM_IN_WHEN,
    RENT_ROOM_IN_DESCRIPTION
}
